<a href="https://colab.research.google.com/github/loouisbrandon/Titanic_learning/blob/main/Titanic_valid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd 
import numpy as np 

In [28]:
def transformar_sexo(valor):
    if valor == 'female':
        return 1
    else:
        return 0

In [38]:
train = pd.read_csv("/content/drive/MyDrive/titanic/train.csv")#NÃO ESQUECER DE VERIFICAR O CAMINHO 
test = pd.read_csv("/content/drive/MyDrive/titanic/test.csv")

train['Sex_binary'] = train['Sex'].map(transformar_sexo)
test['Sex_binary'] = test['Sex'].map(transformar_sexo)

variaveis = ['Sex_binary', 'Age']

X = train[variaveis].fillna(-1)
y = train['Survived']

In [40]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_binary  
0      0         A/5 21171   7.2500   NaN        S           0  
1      0          PC 17599  71.2833   C85        C           1  
2      0  STON/O2. 3101282   7.9250   NaN        S           1  
3      0            113803  53.1000  C123        S           1  
4      0            373450   8.0500   NaN        S           0

In [41]:
from sklearn.ensemble import RandomForestClassifier #Primeiro teste
from sklearn.model_selection import train_test_split #Segundo teste 

In [53]:
X_falso = np.arange(10)
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.random.seed(0)#Gerando numeros aleatorios em uma ordem padrão
train_test_split(x_falso, test_size=0.5)#importante para controlar a aleatoriedade da divisão

[array([6, 7, 3, 0, 5]), array([2, 8, 4, 9, 1])]

In [44]:
np.random.seed(1)
X_treino, X_valid, y_treino, y_valid = train_test_split(X, y, test_size=0.5)

In [45]:
X_treino.head()

Sex_binary    Age
394           1  24.00
851           0  74.00
373           0  22.00
523           1  44.00
78            0   0.83

In [46]:
X_treino.shape, X_valid.shape, y_treino.shape, y_valid.shape

((445, 2), (446, 2), (445,), (446,))

In [47]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0) #Utilizando 100 arvores para o modelo / random state é a mesma coisa de random seed 
modelo.fit(X_treino, y_treino)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [48]:
p = modelo.predict(X_valid)

In [49]:
np.mean(y_valid == p)

0.7466367713004485

In [50]:
p = (X_valid['Sex_binary'] == 1).astype(np.int64)
np.mean(y_valid == p)

0.7623318385650224

#validação cruzada

In [54]:
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
from sklearn.model_selection import KFold #na cross validation cada divisão é chamada de fold 

In [62]:
kf = KFold(3, shuffle=True, random_state=0)
for linhas_treino, linhas_valid in kf.split(X_falso):
  print("Treino:", linhas_treino)
  print("Valid:", linhas_valid)
  print()

Treino: [0 1 3 5 6 7]
Valid: [2 4 8 9]

Treino: [0 2 3 4 5 8 9]
Valid: [1 6 7]

Treino: [1 2 4 6 7 8 9]
Valid: [0 3 5]



In [70]:
resultados = []
for rep in range(10):
    print("Rep:", rep)
    kf = KFold(5, shuffle=True, random_state=rep)
    
    for linhas_treino, linhas_valid in kf.split(X):
        print("Treino:", linhas_treino.shape[0])
        print("Valid:", linhas_valid.shape[0])

        X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
        y_treino, y_valid = y.iloc[linhas_treino], y.iloc[linhas_valid]

        modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
        modelo.fit(X_treino, y_treino)

        p = modelo.predict(X_valid)

        acc = np.mean(y_valid == p)
        resultados.append(acc)
        print("Acc:", acc)
        print()
        #print(X_treino.head())
        #print()

Rep: 0
Treino: 712
Valid: 179
Acc: 0.7988826815642458

Treino: 713
Valid: 178
Acc: 0.7359550561797753

Treino: 713
Valid: 178
Acc: 0.7808988764044944

Treino: 713
Valid: 178
Acc: 0.797752808988764

Treino: 713
Valid: 178
Acc: 0.7808988764044944

Rep: 1
Treino: 712
Valid: 179
Acc: 0.7374301675977654

Treino: 713
Valid: 178
Acc: 0.7247191011235955

Treino: 713
Valid: 178
Acc: 0.7808988764044944

Treino: 713
Valid: 178
Acc: 0.7921348314606742

Treino: 713
Valid: 178
Acc: 0.7921348314606742

Rep: 2
Treino: 712
Valid: 179
Acc: 0.7653631284916201

Treino: 713
Valid: 178
Acc: 0.7865168539325843

Treino: 713
Valid: 178
Acc: 0.7865168539325843

Treino: 713
Valid: 178
Acc: 0.7808988764044944

Treino: 713
Valid: 178
Acc: 0.7640449438202247

Rep: 3
Treino: 712
Valid: 179
Acc: 0.7653631284916201

Treino: 713
Valid: 178
Acc: 0.7471910112359551

Treino: 713
Valid: 178
Acc: 0.7808988764044944

Treino: 713
Valid: 178
Acc: 0.7415730337078652

Treino: 713
Valid: 178
Acc: 0.8202247191011236

Rep: 4
Treino

In [71]:
np.mean(resultados)

0.7692593057560732

#Criar submission


In [ ]:
variaveis = ['Sex_binary', 'Age']

In [ ]:
def transformar_sexo(valor):
  if valor == 'female':
    return 1 
  else: 
    return 0

train['Sex_binary'] = train['Sex'].map(transformar_sexo)

In [ ]:
train.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                     

In [ ]:
variaveis = ['Sex_binary', 'Age']

In [ ]:
x = train[variaveis]

y = train ['Survived']

In [ ]:
x.head

<bound method NDFrame.head of      Sex_binary   Age
0             0  34.5
1             1  47.0
2             0  62.0
3             0  27.0
4             1  22.0
..          ...   ...
413           0   NaN
414           1  39.0
415           0  38.5
416           0   NaN
417           0   NaN

[418 rows x 2 columns]>

In [ ]:
y.head 

<bound method NDFrame.head of 0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64>

In [ ]:
x = x.fillna(-1) 

In [ ]:
modelo.fit(x, y)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [ ]:
test['Sex_binary'] = test['Sex'].map(transformar_sexo)

In [ ]:
x_prev = test[variaveis]
x_prev = x_prev.fillna(-1)
x_prev.head()

Sex_binary   Age
0           0  34.5
1           1  47.0
2           0  62.0
3           0  27.0
4           1  22.0

In [ ]:
p = modelo.predict(x_prev)
p

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_binary  
0  34.5      0      0   330911   7.8292   NaN        Q           0  
1  47.0      1      0   363272   7.0000   NaN        S           1  
2  62.0      0      0   240276   9.6875   NaN        Q           0  
3  27.0      0      0   315154   8.6625   NaN        S           0  
4  22.0      1      1  3101298  12.2875   NaN        S           1

In [ ]:
sub = pd.Series(p, index=test['PassengerId'], name='Survived')
sub.shape

(418,)

In [ ]:
sub.to_csv("First_model.csv", header=True)

In [ ]:
!head -n10 First_model.csv

PassengerId,Survived
892,0
893,1
894,0
895,1
896,1
897,0
898,1
899,0
900,1
